// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: encounter-service/encounter-service.proto

package encounter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId          int32  `protobuf:"varint,1,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	Description       string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Id                int32  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	Latitude          int32  `protobuf:"varint,4,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude         int32  `protobuf:"varint,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Name              string `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Status            string `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Type              string `protobuf:"bytes,8,opt,name=Type,proto3" json:"Type,omitempty"`
	XP                int32  `protobuf:"varint,9,opt,name=XP,proto3" json:"XP,omitempty"`
	LocationLongitude int32  `protobuf:"varint,10,opt,name=LocationLongitude,proto3" json:"LocationLongitude,omitempty"`
	LocationLatitude  int32  `protobuf:"varint,11,opt,name=LocationLatitude,proto3" json:"LocationLatitude,omitempty"`
	Image             string `protobuf:"bytes,12,opt,name=Image,proto3" json:"Image,omitempty"`
	Range             int32  `protobuf:"varint,13,opt,name=Range,proto3" json:"Range,omitempty"`
	RequiredPeople    int32  `protobuf:"varint,14,opt,name=RequiredPeople,proto3" json:"RequiredPeople,omitempty"`
	CheckPointId      int32  `protobuf:"varint,15,opt,name=CheckPointId,proto3" json:"CheckPointId,omitempty"`
}

func (x *Encounter) Reset() {
	*x = Encounter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encounter) ProtoMessage() {}

func (x *Encounter) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encounter.ProtoReflect.Descriptor instead.
func (*Encounter) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{0}
}

func (x *Encounter) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Encounter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Encounter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Encounter) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Encounter) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Encounter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Encounter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Encounter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Encounter) GetXP() int32 {
	if x != nil {
		return x.XP
	}
	return 0
}

func (x *Encounter) GetLocationLongitude() int32 {
	if x != nil {
		return x.LocationLongitude
	}
	return 0
}

func (x *Encounter) GetLocationLatitude() int32 {
	if x != nil {
		return x.LocationLatitude
	}
	return 0
}

func (x *Encounter) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Encounter) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *Encounter) GetRequiredPeople() int32 {
	if x != nil {
		return x.RequiredPeople
	}
	return 0
}

func (x *Encounter) GetCheckPointId() int32 {
	if x != nil {
		return x.CheckPointId
	}
	return 0
}

type GetEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEncounterRequest) Reset() {
	*x = GetEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncounterRequest) ProtoMessage() {}

func (x *GetEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncounterRequest.ProtoReflect.Descriptor instead.
func (*GetEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetEncounterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *GetEncounterResponse) Reset() {
	*x = GetEncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncounterResponse) ProtoMessage() {}

func (x *GetEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncounterResponse.ProtoReflect.Descriptor instead.
func (*GetEncounterResponse) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEncounterResponse) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type UpsertEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *UpsertEncounterRequest) Reset() {
	*x = UpsertEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEncounterRequest) ProtoMessage() {}

func (x *UpsertEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEncounterRequest.ProtoReflect.Descriptor instead.
func (*UpsertEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertEncounterRequest) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type UpsertEncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *UpsertEncounterResponse) Reset() {
	*x = UpsertEncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEncounterResponse) ProtoMessage() {}

func (x *UpsertEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEncounterResponse.ProtoReflect.Descriptor instead.
func (*UpsertEncounterResponse) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertEncounterResponse) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type DeleteEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEncounterRequest) Reset() {
	*x = DeleteEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEncounterRequest) ProtoMessage() {}

func (x *DeleteEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEncounterRequest.ProtoReflect.Descriptor instead.
func (*DeleteEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEncounterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteEncounterResponse) Reset() {
	*x = DeleteEncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEncounterResponse) ProtoMessage() {}

func (x *DeleteEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEncounterResponse.ProtoReflect.Descriptor instead.
func (*DeleteEncounterResponse) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{6}
}

var File_encounter_service_encounter_service_proto protoreflect.FileDescriptor

var file_encounter_service_encounter_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x03, 0x0a, 0x09, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x58, 0x50, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x58, 0x50, 0x12,
	0x2c, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2a, 0x0a,
	0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x16, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x43,
	0x0a, 0x17, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x65, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa4, 0x02, 0x0a, 0x10, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x14, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x5b, 0x0a, 0x0f, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x3a, 0x01, 0x2a, 0x22, 0x0a, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x5d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a, 0x0f,
	0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42,
	0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounter_service_encounter_service_proto_rawDescOnce sync.Once
	file_encounter_service_encounter_service_proto_rawDescData = file_encounter_service_encounter_service_proto_rawDesc
)

func file_encounter_service_encounter_service_proto_rawDescGZIP() []byte {
	file_encounter_service_encounter_service_proto_rawDescOnce.Do(func() {
		file_encounter_service_encounter_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounter_service_encounter_service_proto_rawDescData)
	})
	return file_encounter_service_encounter_service_proto_rawDescData
}

var file_encounter_service_encounter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_encounter_service_encounter_service_proto_goTypes = []interface{}{
	(*Encounter)(nil),               // 0: Encounter
	(*GetEncounterRequest)(nil),     // 1: GetEncounterRequest
	(*GetEncounterResponse)(nil),    // 2: GetEncounterResponse
	(*UpsertEncounterRequest)(nil),  // 3: UpsertEncounterRequest
	(*UpsertEncounterResponse)(nil), // 4: UpsertEncounterResponse
	(*DeleteEncounterRequest)(nil),  // 5: DeleteEncounterRequest
	(*DeleteEncounterResponse)(nil), // 6: DeleteEncounterResponse
}
var file_encounter_service_encounter_service_proto_depIdxs = []int32{
	0, // 0: GetEncounterResponse.encounter:type_name -> Encounter
	0, // 1: UpsertEncounterRequest.encounter:type_name -> Encounter
	0, // 2: UpsertEncounterResponse.encounter:type_name -> Encounter
	1, // 3: EncounterService.GetEncounter:input_type -> GetEncounterRequest
	3, // 4: EncounterService.UpsertEncounter:input_type -> UpsertEncounterRequest
	5, // 5: EncounterService.DeleteEncounter:input_type -> DeleteEncounterRequest
	2, // 6: EncounterService.GetEncounter:output_type -> GetEncounterResponse
	4, // 7: EncounterService.UpsertEncounter:output_type -> UpsertEncounterResponse
	6, // 8: EncounterService.DeleteEncounter:output_type -> DeleteEncounterResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_encounter_service_encounter_service_proto_init() }
func file_encounter_service_encounter_service_proto_init() {
	if File_encounter_service_encounter_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounter_service_encounter_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Encounter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertEncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounter_service_encounter_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounter_service_encounter_service_proto_goTypes,
		DependencyIndexes: file_encounter_service_encounter_service_proto_depIdxs,
		MessageInfos:      file_encounter_service_encounter_service_proto_msgTypes,
	}.Build()
	File_encounter_service_encounter_service_proto = out.File
	file_encounter_service_encounter_service_proto_rawDesc = nil
	file_encounter_service_encounter_service_proto_goTypes = nil
	file_encounter_service_encounter_service_proto_depIdxs = nil
}
